insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 83);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 175);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 29);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 134);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de jazz dans un club intimiste', 11);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 42);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 282);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 139);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 25);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 92);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 26);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 220);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 8);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 59);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 146);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 275);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 263);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 121);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 95);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 125);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 279);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 91);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 125);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 263);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 100);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 103);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 202);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 202);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 236);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 9);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 124);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 172);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 151);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 298);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 80);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 210);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 221);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 276);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 278);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 13);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 222);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 67);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 265);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 66);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 216);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 79);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 233);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 280);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 256);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 171);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 5);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 206);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 219);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de jazz dans un club intimiste', 77);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 25);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 160);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de jazz dans un club intimiste', 291);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 40);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 104);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 198);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 234);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 242);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 287);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 90);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 79);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 54);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 57);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 300);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de jazz dans un club intimiste', 0);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 299);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 292);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 172);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 237);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 86);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 76);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 100);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de jazz dans un club intimiste', 53);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Festival de musique électronique avec des DJ internationaux', 221);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée dansante avec un DJ résident', 235);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 248);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de rock en plein air avec des groupes locaux', 63);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Soirée karaoké avec des amis', 112);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 168);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de hip-hop avec des rappeurs célèbres', 43);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 270);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 187);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de reggae sur la plage avec des artistes locaux', 186);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Fête de la musique dans la rue avec des artistes locaux', 82);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert de musique classique dans une salle de concert prestigieuse', 213);
insert into MOCK_DATA (id_event, description, prix_billet) values ('error: Function ''lookup'' not found', 'Concert acoustique dans un café', 147);
